name: Example Workflow Using SecureStack Actionz
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Exposure Analysis Step
        id: exposure
        uses: SecureStackCo/actions-exposure@v0.1.0
        with:
          securestack_api_key: ${{ secrets.SECURESTACK_API_KEY_SECRET }}
          securestack_app_id: 'a9ad205b-d519-4a95-833d-304b6e82be21'
          severity: critical
          flags: '--dom -r'
