name: Example Workflow Using SecureStack Actions
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repoo for running secrets analysis within workflow
        id: checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Exposure Analysis Step
        id: exposure
        uses: SecureStackCo/actions-exposure@main
        with:
          securestack_api_key: ${{ secrets.SECURESTACK_API_KEY_SECRET }}
          securestack_app_id: '3164cc31-80ad-40a8-924d-9667058ad250'
          severity: critical
          flags: '--dom -r'
